# Generated by Django 4.1.2 on 2022-10-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FamilyMember',
            new_name='Member',
        ),
    ]
